from flask import Flask, request, jsonify
from flask_cors import CORS
import joblib
import os
import re
import json
import numpy as np
from preprocess import clean_resume

app = Flask(__name__)
CORS(app)

# --- DIRECTORY CONFIGURATIONS ---
MODEL_DIR = 'model'
VECTORIZER_PATH = os.path.join(MODEL_DIR, 'vectorizer.pkl')
METRICS_PATH = os.path.join(MODEL_DIR, 'model_metrics.json')

# Dictionary to store loaded models in memory
loaded_models = {}

# Map clean identifier names from frontend to file names generated by train_model.py
MODEL_MAPPING = {
    "Naive Bayes": "model_naive_bayes.pkl",
    "Logistic Regression": "model_logistic_regression.pkl",
    "Random Forest": "model_random_forest.pkl",
    "Support Vector Machine": "model_support_vector_machine.pkl",
    "K-Nearest Neighbors": "model_k-nearest_neighbors.pkl"
}

# --- LAZY LOADING ALL CLASSIFIERS ---
try:
    vectorizer = joblib.load(VECTORIZER_PATH)
    print(" Core Text Vectorizer Loaded!")
    
    # Load all 5 operational models dynamically
    for friendly_name, filename in MODEL_MAPPING.items():
        full_path = os.path.join(MODEL_DIR, filename)
        if os.path.exists(full_path):
            loaded_models[friendly_name] = joblib.load(full_path)
            print(f"    Armed Classifier Engine: {friendly_name}")
        else:
            print(f"    Warning: Missing binary for {friendly_name} at {full_path}")
            
except Exception as e:
    print(f" Initialization Error: {e}. Ensure you run train_model.py first!")


# --- FULL JOB ROLE DATABASE (Matches Frontend Dropdown) ---
JOB_REQUIREMENTS = {
    # Data & AI
    "Data Scientist": ["Python", "Machine Learning", "Pandas", "NumPy", "Scikit-Learn", "Statistics", "SQL", "Data Visualization"],
    "Data Analyst": ["SQL", "Python", "Tableau", "PowerBI", "Excel", "Statistics", "Data Cleaning"],
    "Data Engineer": ["Python", "SQL", "ETL", "Spark", "Hadoop", "AWS", "Big Data", "Data Pipelines"],
    "ML Engineer": ["Python", "Machine Learning", "PyTorch", "TensorFlow", "Scikit-Learn", "NLP", "Computer Vision"],
    "AI Engineer": ["Python", "OpenAI", "Generative AI", "LLMs", "Deep Learning", "Neural Networks", "NLP"],
    "Machine Learning Engineer": ["Python", "TensorFlow", "PyTorch", "Scikit-Learn", "Deployment", "Algorithms"],

    # Development
    "Frontend Developer": ["React", "JavaScript", "HTML", "CSS", "Tailwind", "Next.js", "TypeScript", "Redux"],
    "Backend Developer": ["Node.js", "Express", "Python", "Django", "SQL", "API Design", "Docker", "Java"],
    "Full Stack Developer": ["React", "Node.js", "Express", "SQL", "JavaScript", "MongoDB", "HTML", "CSS"],
    "MERN Stack Developer": ["MongoDB", "Express", "React", "Node.js", "JavaScript", "Redux", "REST API"],
    "React Developer": ["React", "JavaScript", "Redux", "Hooks", "Context API", "Tailwind", "HTML", "CSS"],
    "Web Developer": ["HTML", "CSS", "JavaScript", "PHP", "Bootstrap", "WordPress", "SQL"],
    "Mobile App Developer": ["Flutter", "React Native", "Dart", "Swift", "Kotlin", "Firebase", "Mobile UI"],
    "Android Developer": ["Kotlin", "Java", "Android Studio", "Firebase", "SQLite", "XML", "Coroutines"],
    "Software Engineer": ["C++", "Java", "Data Structures", "Algorithms", "Software Design", "Unit Testing", "Git"],
    "Game Developer": ["Unity", "C#", "C++", "Unreal Engine", "Shaders", "Game Design", "Physics"],

    # Cloud & Cybersecurity
    "DevOps Engineer": ["Docker", "Kubernetes", "AWS", "CI/CD", "Linux", "Jenkins", "Terraform", "Git"],
    "Cloud Engineer": ["AWS", "Azure", "Cloud Computing", "Linux", "Terraform", "Networking", "Serverless"],
    "Cybersecurity Analyst": ["Network Security", "Ethical Hacking", "Firewalls", "Penetration Testing", "SIEM", "Linux"],
    "Cybersecurity Specialist": ["Cryptography", "Network Security", "Security Auditing", "Incident Response"],
    "Network Engineer": ["Cisco", "TCP/IP", "Routing", "Switching", "Firewalls", "VPN", "DNS"],
    "System Administrator": ["Linux", "Windows Server", "Networking", "Security", "Bash", "Active Directory"],

    # Design & Business
    "UI/UX Designer": ["Figma", "Adobe XD", "User Research", "Wireframing", "Prototyping", "User Experience"],
    "Graphic Designer": ["Photoshop", "Illustrator", "Branding", "Typography", "Adobe Creative Suite"],
    "Product Manager": ["Agile", "Scrum", "Jira", "Risk Management", "Roadmapping", "Product Strategy"],
    "Project Manager": ["Project Planning", "Budgeting", "Stakeholder Management", "Jira", "Agile"],
    "HR Manager": ["Recruitment", "Employee Relations", "Payroll", "Onboarding", "Policy Development"],
    "Digital Marketing Specialist": ["SEO", "SEM", "Google Analytics", "Social Media Marketing", "Content Strategy"],
    "Sales Manager": ["Lead Generation", "CRM", "Negotiation", "Sales Strategy", "Communication"]
}

def extract_details(text, target_role):
    all_tech_keywords = [
        'Python', 'Java', 'React', 'Node.js', 'MongoDB', 'SQL', 'C++', 'C#',
        'Machine Learning', 'Data Science', 'Docker', 'AWS', 'Azure', 'GCP',
        'Git', 'JavaScript', 'HTML', 'CSS', 'Pandas', 'NumPy', 'Flutter',
        'Figma', 'Express', 'TypeScript', 'Next.js', 'NLP', 'TensorFlow', 
        'PyTorch', 'Scikit-Learn', 'Unity', 'Solidity', 'ETL', 'Jenkins', 
        'Kubernetes', 'Tableau', 'PowerBI', 'Redux', 'Kotlin', 'Swift'
    ]
    
    text_lower = text.lower()
    found_skills = [s for s in all_tech_keywords if s.lower() in text_lower]
    
    required = JOB_REQUIREMENTS.get(target_role, [])
    matched_skills = [s for s in required if s.lower() in text_lower]
    missing_skills = [s for s in required if s.lower() not in text_lower]
    
    skill_score = (len(matched_skills) / len(required)) * 100 if required else 0

    education = "Not Found"
    if re.search(r'(Bachelor|Master|BS|MS|B\.Tech|University|College|Education)', text, re.I):
        education = "University Graduate"
        
    experience = "Fresher / Entry Level"
    if re.search(r'(Years?|Exp|Worked at|Experience|Manager|Lead|Intern)', text, re.I):
        experience = "Professional Experience Found"

    return {
        "found_skills": found_skills,
        "missing_skills": missing_skills,
        "skill_score": skill_score,
        "summary": {"education": education, "experience": experience}
    }

# --- ROUTE 1: METRICS ENDPOINT FOR BATTLE BOARD ---
@app.route('/metrics', methods=['GET'])
def get_metrics():
    try:
        if os.path.exists(METRICS_PATH):
            with open(METRICS_PATH, 'r') as f:
                data = json.load(f)
            return jsonify(data)
        else:
            return jsonify({"error": "Metrics file not found. Run train_model.py first."}), 404
    except Exception as e:
        return jsonify({"error": str(e)}), 500

# --- ROUTE 2: PREDICT ENDPOINT WITH SWITCHABLE INTERFACE ---
@app.route('/predict', methods=['POST'])
def predict():
    try:
        data = request.get_json()
        resume_text = data.get('resume_text', '')
        target_role = data.get('target_role', '')
        selected_classifier = data.get('classifier', 'Naive Bayes')
        
        if not resume_text:
            return jsonify({'error': 'No text provided'}), 400

        if selected_classifier not in loaded_models:
            return jsonify({'error': f"Model '{selected_classifier}' is unavailable or not trained."}), 400
            
        current_model = loaded_models[selected_classifier]

        # 1. ML Classification using chosen algorithm
        cleaned_text = clean_resume(resume_text)
        vectorized_text = vectorizer.transform([cleaned_text])
        predicted_category = current_model.predict(vectorized_text)[0]
        
        # --- NEW: DYNAMIC PROBABILITY CALCULATOR ---
        # Har algorithm ki apni calculation confidence value nikalna
        try:
            probabilities = current_model.predict_proba(vectorized_text)[0]
            ml_confidence = max(probabilities) * 100
        except:
            # KNN or linear models with no direct probability fallback
            ml_confidence = 75.0  

        # 2. Extract relative keyword requirements
        details = extract_details(resume_text, target_role)
        
        # --- NEW DYNAMIC ENSEMBLE SCORE FORMULA ---
        # Ab hum 'Fuzzy Matching' use karenge taake agar partial words bhi match hon (e.g. "Data Scientist" vs "Data Science") toh bonus miley
        target_tokens = set(target_role.lower().split())
        pred_tokens = set(predicted_category.lower().split())
        token_overlap = target_tokens.intersection(pred_tokens)
        
        # Base role bonus changes dynamically based on label similarity
        if token_overlap:
            role_match_bonus = 35
        elif predicted_category.lower() in target_role.lower() or target_role.lower() in predicted_category.lower():
            role_match_bonus = 35
        else:
            role_match_bonus = 10 # Soft cushion instead of a hard 0

        # Math Engine: 40% Skills + 35% Role Match Logic + 25% Pure ML Confidence Probability
        final_confidence = (details['skill_score'] * 0.40) + role_match_bonus + (ml_confidence * 0.25)
        
        # Final formatting caps
        final_confidence = min(98, round(final_confidence, 2))

        prediction_verdict = "Likely Accepted" if final_confidence > 65 else "Low Compatibility"

        return jsonify({
            'prediction': prediction_verdict,
            'confidence': final_confidence,
            'ml_detected_role': predicted_category,
            'skills': details['found_skills'],
            'missing_skills': details['missing_skills'],
            'summary': details['summary']
        })

    except Exception as e:
        print(f"❌ Error during inference execution: {e}")
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True, port=5000)